// Generated by tools/generate-api-spec.mjs. Do not edit.

struct GeneratedAPITypeContract {
  let instanceProperties: [String]
  let instanceMethods: [String]
  let asyncInstanceMethods: [String]
  let staticMethods: [String]
  let asyncStaticMethods: [String]
  let runtimeMembers: [String]
}

let generatedAPIContract: [String: GeneratedAPITypeContract] = [
  "Alert": GeneratedAPITypeContract(
    instanceProperties: ["message", "title"],
    instanceMethods: [
      "addAction", "addCancelAction", "addDestructiveAction", "addSecureTextField", "addTextField",
      "textFieldValue",
    ],
    asyncInstanceMethods: ["present", "presentAlert", "presentSheet"],
    staticMethods: [],
    asyncStaticMethods: [],
    runtimeMembers: [
      "title", "message", "addAction", "addDestructiveAction", "addCancelAction", "addTextField",
      "addSecureTextField", "textFieldValue", "present", "presentAlert", "presentSheet",
    ]
  ),
  "Calendar": GeneratedAPITypeContract(
    instanceProperties: [
      "allowsContentModifications", "color", "identifier", "isSubscribed", "title",
    ],
    instanceMethods: ["remove", "save", "supportsAvailability"],
    asyncInstanceMethods: [],
    staticMethods: [],
    asyncStaticMethods: [
      "createForReminders", "defaultForEvents", "defaultForReminders", "findOrCreateForReminders",
      "forEvents", "forEventsByTitle", "forReminders", "forRemindersByTitle", "presentPicker",
    ],
    runtimeMembers: [
      "identifier", "title", "isSubscribed", "allowsContentModifications", "color",
      "supportsAvailability", "save", "remove", "forReminders", "forEvents", "forRemindersByTitle",
      "forEventsByTitle", "createForReminders", "findOrCreateForReminders", "defaultForReminders",
      "defaultForEvents", "presentPicker",
    ]
  ),
  "CalendarEvent": GeneratedAPITypeContract(
    instanceProperties: [
      "attendees", "availability", "calendar", "endDate", "identifier", "isAllDay", "location",
      "notes", "startDate", "timeZone", "title",
    ],
    instanceMethods: ["addRecurrenceRule", "remove", "removeAllRecurrenceRules", "save"],
    asyncInstanceMethods: ["presentEdit"],
    staticMethods: [],
    asyncStaticMethods: [
      "between", "lastWeek", "nextWeek", "presentCreate", "thisWeek", "today", "tomorrow",
      "yesterday",
    ],
    runtimeMembers: [
      "identifier", "title", "location", "notes", "startDate", "endDate", "isAllDay", "attendees",
      "availability", "timeZone", "calendar", "addRecurrenceRule", "removeAllRecurrenceRules",
      "save", "remove", "presentEdit", "presentCreate", "today", "tomorrow", "yesterday",
      "thisWeek", "nextWeek", "lastWeek", "between",
    ]
  ),
  "CallbackURL": GeneratedAPITypeContract(
    instanceProperties: [],
    instanceMethods: ["addParameter", "getURL"],
    asyncInstanceMethods: ["open"],
    staticMethods: [],
    asyncStaticMethods: [],
    runtimeMembers: ["addParameter", "open", "getURL"]
  ),
  "Color": GeneratedAPITypeContract(
    instanceProperties: ["alpha", "blue", "green", "hex", "red"],
    instanceMethods: [],
    asyncInstanceMethods: [],
    staticMethods: [
      "black", "blue", "brown", "clear", "cyan", "darkGray", "dynamic", "gray", "green",
      "lightGray", "magenta", "orange", "purple", "red", "white", "yellow",
    ],
    asyncStaticMethods: [],
    runtimeMembers: [
      "hex", "red", "green", "blue", "alpha", "black", "darkGray", "lightGray", "white", "gray",
      "red", "green", "blue", "cyan", "yellow", "magenta", "orange", "purple", "brown", "clear",
      "dynamic",
    ]
  ),
  "Contact": GeneratedAPITypeContract(
    instanceProperties: [
      "birthday", "dates", "departmentName", "emailAddresses", "familyName", "givenName",
      "identifier", "image", "isBirthdayAvailable", "isDatesAvailable", "isDepartmentNameAvailable",
      "isEmailAddressesAvailable", "isFamilyNameAvailable", "isGiveNameAvailable",
      "isImageAvailable", "isJobTitleAvailable", "isMiddleNameAvailable", "isNamePrefixAvailable",
      "isNicknameAvailable", "isNoteAvailable", "isOrganizationNameAvailable",
      "isPhoneNumbersAvailable", "isPostalAddressesAvailable", "isSocialProfilesAvailable",
      "isURLAddressesAvailable", "jobTitle", "middleName", "namePrefix", "nickname", "note",
      "organizationName", "phoneNumbers", "postalAddresses", "socialProfiles", "urlAddresses",
    ],
    instanceMethods: [],
    asyncInstanceMethods: [],
    staticMethods: ["add", "delete", "update"],
    asyncStaticMethods: ["all", "inGroups", "persistChanges"],
    runtimeMembers: [
      "identifier", "namePrefix", "givenName", "middleName", "familyName", "nickname", "birthday",
      "image", "emailAddresses", "phoneNumbers", "postalAddresses", "socialProfiles", "note",
      "urlAddresses", "dates", "organizationName", "departmentName", "jobTitle",
      "isNamePrefixAvailable", "isGiveNameAvailable", "isMiddleNameAvailable",
      "isFamilyNameAvailable", "isNicknameAvailable", "isBirthdayAvailable",
      "isEmailAddressesAvailable", "isPhoneNumbersAvailable", "isPostalAddressesAvailable",
      "isSocialProfilesAvailable", "isImageAvailable", "isNoteAvailable", "isURLAddressesAvailable",
      "isOrganizationNameAvailable", "isDepartmentNameAvailable", "isJobTitleAvailable",
      "isDatesAvailable", "all", "inGroups", "add", "update", "delete", "persistChanges",
    ]
  ),
  "ContactsContainer": GeneratedAPITypeContract(
    instanceProperties: ["identifier", "name"],
    instanceMethods: [],
    asyncInstanceMethods: [],
    staticMethods: [],
    asyncStaticMethods: ["all", "default", "withIdentifier"],
    runtimeMembers: ["identifier", "name", "default", "all", "withIdentifier"]
  ),
  "ContactsGroup": GeneratedAPITypeContract(
    instanceProperties: ["identifier", "name"],
    instanceMethods: ["addMember", "removeMember"],
    asyncInstanceMethods: [],
    staticMethods: ["add", "delete", "update"],
    asyncStaticMethods: ["all"],
    runtimeMembers: [
      "identifier", "name", "all", "addMember", "removeMember", "add", "update", "delete",
    ]
  ),
  "Data": GeneratedAPITypeContract(
    instanceProperties: [],
    instanceMethods: ["getBytes", "toBase64String", "toRawString"],
    asyncInstanceMethods: [],
    staticMethods: [
      "fromBase64String", "fromBytes", "fromFile", "fromJPEG", "fromPNG", "fromString",
    ],
    asyncStaticMethods: [],
    runtimeMembers: [
      "fromString", "fromFile", "fromBase64String", "fromJPEG", "fromPNG", "fromBytes",
      "toRawString", "toBase64String", "getBytes",
    ]
  ),
  "DateFormatter": GeneratedAPITypeContract(
    instanceProperties: ["dateFormat", "locale"],
    instanceMethods: [
      "date", "string", "useFullDateStyle", "useFullTimeStyle", "useLongDateStyle",
      "useLongTimeStyle", "useMediumDateStyle", "useMediumTimeStyle", "useNoDateStyle",
      "useNoTimeStyle", "useShortDateStyle", "useShortTimeStyle",
    ],
    asyncInstanceMethods: [],
    staticMethods: [],
    asyncStaticMethods: [],
    runtimeMembers: [
      "dateFormat", "locale", "string", "date", "useNoDateStyle", "useShortDateStyle",
      "useMediumDateStyle", "useLongDateStyle", "useFullDateStyle", "useNoTimeStyle",
      "useShortTimeStyle", "useMediumTimeStyle", "useLongTimeStyle", "useFullTimeStyle",
    ]
  ),
  "DatePicker": GeneratedAPITypeContract(
    instanceProperties: [
      "countdownDuration", "initialDate", "maximumDate", "minimumDate", "minuteInterval",
    ],
    instanceMethods: [],
    asyncInstanceMethods: ["pickCountdownDuration", "pickDate", "pickDateAndTime", "pickTime"],
    staticMethods: [],
    asyncStaticMethods: [],
    runtimeMembers: [
      "minimumDate", "maximumDate", "countdownDuration", "minuteInterval", "initialDate",
      "pickTime", "pickDate", "pickDateAndTime", "pickCountdownDuration",
    ]
  ),
  "Device": GeneratedAPITypeContract(
    instanceProperties: [],
    instanceMethods: [],
    asyncInstanceMethods: [],
    staticMethods: [
      "batteryLevel", "isCharging", "isDischarging", "isFaceDown", "isFaceUp", "isFullyCharged",
      "isInLandscapeLeft", "isInLandscapeRight", "isInPortrait", "isInPortraitUpsideDown", "isPad",
      "isPhone", "isUsingDarkAppearance", "language", "locale", "model", "name",
      "preferredLanguages", "screenBrightness", "screenResolution", "screenScale", "screenSize",
      "setScreenBrightness", "systemName", "systemVersion", "volume",
    ],
    asyncStaticMethods: [],
    runtimeMembers: [
      "name", "systemName", "systemVersion", "model", "isPhone", "isPad", "screenSize",
      "screenResolution", "screenScale", "screenBrightness", "isInPortrait",
      "isInPortraitUpsideDown", "isInLandscapeLeft", "isInLandscapeRight", "isFaceUp", "isFaceDown",
      "batteryLevel", "isDischarging", "isCharging", "isFullyCharged", "preferredLanguages",
      "locale", "language", "isUsingDarkAppearance", "volume", "setScreenBrightness",
    ]
  ),
  "Dictation": GeneratedAPITypeContract(
    instanceProperties: [],
    instanceMethods: [],
    asyncInstanceMethods: [],
    staticMethods: [],
    asyncStaticMethods: ["start"],
    runtimeMembers: ["start"]
  ),
  "DocumentPicker": GeneratedAPITypeContract(
    instanceProperties: [],
    instanceMethods: [],
    asyncInstanceMethods: [],
    staticMethods: [],
    asyncStaticMethods: [
      "export", "exportData", "exportImage", "exportString", "open", "openFile", "openFolder",
    ],
    runtimeMembers: [
      "open", "openFile", "openFolder", "export", "exportString", "exportImage", "exportData",
    ]
  ),
  "DrawContext": GeneratedAPITypeContract(
    instanceProperties: ["opaque", "respectScreenScale", "size"],
    instanceMethods: [
      "addPath", "drawImageAtPoint", "drawImageInRect", "drawText", "drawTextInRect", "fill",
      "fillEllipse", "fillPath", "fillRect", "getImage", "setFillColor", "setFont", "setFontSize",
      "setLineWidth", "setStrokeColor", "setTextAlignedCenter", "setTextAlignedLeft",
      "setTextAlignedRight", "setTextColor", "stroke", "strokeEllipse", "strokePath", "strokeRect",
    ],
    asyncInstanceMethods: [],
    staticMethods: [],
    asyncStaticMethods: [],
    runtimeMembers: [
      "size", "respectScreenScale", "opaque", "getImage", "drawImageInRect", "drawImageAtPoint",
      "setFillColor", "setStrokeColor", "setLineWidth", "fill", "fillRect", "fillEllipse", "stroke",
      "strokeRect", "strokeEllipse", "addPath", "strokePath", "fillPath", "drawText",
      "drawTextInRect", "setFontSize", "setFont", "setTextColor", "setTextAlignedLeft",
      "setTextAlignedCenter", "setTextAlignedRight",
    ]
  ),
  "FileManager": GeneratedAPITypeContract(
    instanceProperties: [],
    instanceMethods: [
      "addTag", "allExtendedAttributes", "allFileBookmarks", "allTags", "bookmarkedPath",
      "bookmarkExists", "cacheDirectory", "copy", "createDirectory", "creationDate",
      "documentsDirectory", "fileExists", "fileExtension", "fileName", "fileSize", "getUTI",
      "isDirectory", "isFileDownloaded", "isFileStoredIniCloud", "joinPath", "libraryDirectory",
      "listContents", "modificationDate", "move", "read", "readExtendedAttribute", "readImage",
      "readString", "remove", "removeExtendedAttribute", "removeTag", "temporaryDirectory", "write",
      "writeExtendedAttribute", "writeImage", "writeString",
    ],
    asyncInstanceMethods: ["downloadFileFromiCloud"],
    staticMethods: ["iCloud", "local"],
    asyncStaticMethods: [],
    runtimeMembers: [
      "local", "iCloud", "read", "readString", "readImage", "write", "writeString", "writeImage",
      "remove", "move", "copy", "fileExists", "isDirectory", "createDirectory",
      "temporaryDirectory", "cacheDirectory", "documentsDirectory", "libraryDirectory", "joinPath",
      "allTags", "addTag", "removeTag", "readExtendedAttribute", "writeExtendedAttribute",
      "removeExtendedAttribute", "allExtendedAttributes", "getUTI", "listContents", "fileName",
      "fileExtension", "bookmarkedPath", "bookmarkExists", "downloadFileFromiCloud",
      "isFileStoredIniCloud", "isFileDownloaded", "creationDate", "modificationDate", "fileSize",
      "allFileBookmarks",
    ]
  ),
  "Font": GeneratedAPITypeContract(
    instanceProperties: [],
    instanceMethods: [],
    asyncInstanceMethods: [],
    staticMethods: [
      "blackMonospacedSystemFont", "blackRoundedSystemFont", "blackSystemFont", "body",
      "boldMonospacedSystemFont", "boldRoundedSystemFont", "boldSystemFont", "callout", "caption1",
      "caption2", "footnote", "headline", "heavyMonospacedSystemFont", "heavyRoundedSystemFont",
      "heavySystemFont", "italicSystemFont", "largeTitle", "lightMonospacedSystemFont",
      "lightRoundedSystemFont", "lightSystemFont", "mediumMonospacedSystemFont",
      "mediumRoundedSystemFont", "mediumSystemFont", "regularMonospacedSystemFont",
      "regularRoundedSystemFont", "regularSystemFont", "semiboldMonospacedSystemFont",
      "semiboldRoundedSystemFont", "semiboldSystemFont", "subheadline", "systemFont",
      "thinMonospacedSystemFont", "thinRoundedSystemFont", "thinSystemFont", "title1", "title2",
      "title3", "ultraLightMonospacedSystemFont", "ultraLightRoundedSystemFont",
      "ultraLightSystemFont",
    ],
    asyncStaticMethods: [],
    runtimeMembers: [
      "largeTitle", "title1", "title2", "title3", "headline", "subheadline", "body", "callout",
      "footnote", "caption1", "caption2", "systemFont", "ultraLightSystemFont", "thinSystemFont",
      "lightSystemFont", "regularSystemFont", "mediumSystemFont", "semiboldSystemFont",
      "boldSystemFont", "heavySystemFont", "blackSystemFont", "italicSystemFont",
      "ultraLightMonospacedSystemFont", "thinMonospacedSystemFont", "lightMonospacedSystemFont",
      "regularMonospacedSystemFont", "mediumMonospacedSystemFont", "semiboldMonospacedSystemFont",
      "boldMonospacedSystemFont", "heavyMonospacedSystemFont", "blackMonospacedSystemFont",
      "ultraLightRoundedSystemFont", "thinRoundedSystemFont", "lightRoundedSystemFont",
      "regularRoundedSystemFont", "mediumRoundedSystemFont", "semiboldRoundedSystemFont",
      "boldRoundedSystemFont", "heavyRoundedSystemFont", "blackRoundedSystemFont",
    ]
  ),
  "Image": GeneratedAPITypeContract(
    instanceProperties: ["size"],
    instanceMethods: [],
    asyncInstanceMethods: [],
    staticMethods: ["fromData", "fromFile"],
    asyncStaticMethods: [],
    runtimeMembers: ["size", "fromFile", "fromData"]
  ),
  "Keychain": GeneratedAPITypeContract(
    instanceProperties: [],
    instanceMethods: [],
    asyncInstanceMethods: [],
    staticMethods: ["contains", "get", "remove", "set"],
    asyncStaticMethods: [],
    runtimeMembers: ["contains", "set", "get", "remove"]
  ),
  "LinearGradient": GeneratedAPITypeContract(
    instanceProperties: ["colors", "endPoint", "locations", "startPoint"],
    instanceMethods: [],
    asyncInstanceMethods: [],
    staticMethods: [],
    asyncStaticMethods: [],
    runtimeMembers: ["colors", "locations", "startPoint", "endPoint"]
  ),
  "ListWidget": GeneratedAPITypeContract(
    instanceProperties: [
      "addAccessoryWidgetBackground", "backgroundColor", "backgroundGradient", "backgroundImage",
      "refreshAfterDate", "spacing", "url",
    ],
    instanceMethods: [
      "addDate", "addImage", "addSpacer", "addStack", "addText", "setPadding", "useDefaultPadding",
    ],
    asyncInstanceMethods: [
      "presentAccessoryCircular", "presentAccessoryInline", "presentAccessoryRectangular",
      "presentExtraLarge", "presentLarge", "presentMedium", "presentSmall",
    ],
    staticMethods: [],
    asyncStaticMethods: [],
    runtimeMembers: [
      "backgroundColor", "backgroundImage", "backgroundGradient", "addAccessoryWidgetBackground",
      "spacing", "url", "refreshAfterDate", "addText", "addDate", "addImage", "addSpacer",
      "addStack", "setPadding", "useDefaultPadding", "presentSmall", "presentMedium",
      "presentLarge", "presentExtraLarge", "presentAccessoryInline", "presentAccessoryCircular",
      "presentAccessoryRectangular",
    ]
  ),
  "Location": GeneratedAPITypeContract(
    instanceProperties: [],
    instanceMethods: [],
    asyncInstanceMethods: [],
    staticMethods: [
      "reverseGeocode", "setAccuracyToBest", "setAccuracyToHundredMeters", "setAccuracyToKilometer",
      "setAccuracyToTenMeters", "setAccuracyToThreeKilometers",
    ],
    asyncStaticMethods: ["current"],
    runtimeMembers: [
      "current", "setAccuracyToBest", "setAccuracyToTenMeters", "setAccuracyToHundredMeters",
      "setAccuracyToKilometer", "setAccuracyToThreeKilometers", "reverseGeocode",
    ]
  ),
  "Mail": GeneratedAPITypeContract(
    instanceProperties: [
      "bccRecipients", "body", "ccRecipients", "isBodyHTML", "preferredSendingEmailAddress",
      "subject", "toRecipients",
    ],
    instanceMethods: ["addDataAttachment", "addFileAttachment", "addImageAttachment"],
    asyncInstanceMethods: ["send"],
    staticMethods: [],
    asyncStaticMethods: [],
    runtimeMembers: [
      "toRecipients", "ccRecipients", "bccRecipients", "subject", "body", "isBodyHTML",
      "preferredSendingEmailAddress", "send", "addImageAttachment", "addFileAttachment",
      "addDataAttachment",
    ]
  ),
  "Message": GeneratedAPITypeContract(
    instanceProperties: ["body", "recipients"],
    instanceMethods: ["addDataAttachment", "addFileAttachment", "addImageAttachment"],
    asyncInstanceMethods: ["send"],
    staticMethods: [],
    asyncStaticMethods: [],
    runtimeMembers: [
      "recipients", "body", "send", "addImageAttachment", "addFileAttachment", "addDataAttachment",
    ]
  ),
  "Notification": GeneratedAPITypeContract(
    instanceProperties: [
      "actions", "badge", "body", "deliveryDate", "identifier", "nextTriggerDate", "openURL",
      "preferredContentHeight", "scriptName", "sound", "subtitle", "threadIdentifier", "title",
      "userInfo",
    ],
    instanceMethods: ["addAction", "setDailyTrigger", "setTriggerDate", "setWeeklyTrigger"],
    asyncInstanceMethods: ["remove", "schedule"],
    staticMethods: ["current", "resetCurrent"],
    asyncStaticMethods: [
      "allDelivered", "allPending", "removeAllDelivered", "removeAllPending", "removeDelivered",
      "removePending",
    ],
    runtimeMembers: [
      "identifier", "title", "subtitle", "body", "preferredContentHeight", "badge",
      "threadIdentifier", "userInfo", "sound", "openURL", "deliveryDate", "nextTriggerDate",
      "scriptName", "actions", "current", "schedule", "remove", "setTriggerDate", "setDailyTrigger",
      "setWeeklyTrigger", "addAction", "allPending", "allDelivered", "removeAllPending",
      "removeAllDelivered", "removePending", "removeDelivered", "resetCurrent",
    ]
  ),
  "Pasteboard": GeneratedAPITypeContract(
    instanceProperties: [],
    instanceMethods: [],
    asyncInstanceMethods: [],
    staticMethods: ["copy", "copyImage", "copyString", "paste", "pasteImage", "pasteString"],
    asyncStaticMethods: [],
    runtimeMembers: ["copy", "paste", "copyString", "pasteString", "copyImage", "pasteImage"]
  ),
  "Path": GeneratedAPITypeContract(
    instanceProperties: [],
    instanceMethods: [
      "addCurve", "addEllipse", "addLine", "addLines", "addQuadCurve", "addRect", "addRects",
      "addRoundedRect", "closeSubpath", "move",
    ],
    asyncInstanceMethods: [],
    staticMethods: [],
    asyncStaticMethods: [],
    runtimeMembers: [
      "move", "addLine", "addRect", "addEllipse", "addRoundedRect", "addCurve", "addQuadCurve",
      "addLines", "addRects", "closeSubpath",
    ]
  ),
  "Photos": GeneratedAPITypeContract(
    instanceProperties: [],
    instanceMethods: [],
    asyncInstanceMethods: [],
    staticMethods: [
      "removeLatestPhoto", "removeLatestPhotos", "removeLatestScreenshot",
      "removeLatestScreenshots", "save",
    ],
    asyncStaticMethods: [
      "fromCamera", "fromLibrary", "latestPhoto", "latestPhotos", "latestScreenshot",
      "latestScreenshots",
    ],
    runtimeMembers: [
      "fromLibrary", "fromCamera", "latestPhoto", "latestPhotos", "latestScreenshot",
      "latestScreenshots", "removeLatestPhoto", "removeLatestPhotos", "removeLatestScreenshot",
      "removeLatestScreenshots", "save",
    ]
  ),
  "Point": GeneratedAPITypeContract(
    instanceProperties: ["x", "y"],
    instanceMethods: [],
    asyncInstanceMethods: [],
    staticMethods: [],
    asyncStaticMethods: [],
    runtimeMembers: ["x", "y"]
  ),
  "QuickLook": GeneratedAPITypeContract(
    instanceProperties: [],
    instanceMethods: [],
    asyncInstanceMethods: [],
    staticMethods: [],
    asyncStaticMethods: ["present"],
    runtimeMembers: ["present"]
  ),
  "Rect": GeneratedAPITypeContract(
    instanceProperties: [
      "height", "maxX", "maxY", "minX", "minY", "origin", "size", "width", "x", "y",
    ],
    instanceMethods: [],
    asyncInstanceMethods: [],
    staticMethods: [],
    asyncStaticMethods: [],
    runtimeMembers: ["minX", "minY", "maxX", "maxY", "x", "y", "width", "height", "origin", "size"]
  ),
  "RecurrenceRule": GeneratedAPITypeContract(
    instanceProperties: [],
    instanceMethods: [],
    asyncInstanceMethods: [],
    staticMethods: [
      "complexMonthly", "complexMonthlyEndDate", "complexMonthlyOccurrenceCount", "complexWeekly",
      "complexWeeklyEndDate", "complexWeeklyOccurrenceCount", "complexYearly",
      "complexYearlyEndDate", "complexYearlyOccurrenceCount", "daily", "dailyEndDate",
      "dailyOccurrenceCount", "monthly", "monthlyEndDate", "monthlyOccurrenceCount", "weekly",
      "weeklyEndDate", "weeklyOccurrenceCount", "yearly", "yearlyEndDate", "yearlyOccurrenceCount",
    ],
    asyncStaticMethods: [],
    runtimeMembers: [
      "daily", "dailyEndDate", "dailyOccurrenceCount", "weekly", "weeklyEndDate",
      "weeklyOccurrenceCount", "monthly", "monthlyEndDate", "monthlyOccurrenceCount", "yearly",
      "yearlyEndDate", "yearlyOccurrenceCount", "complexWeekly", "complexWeeklyEndDate",
      "complexWeeklyOccurrenceCount", "complexMonthly", "complexMonthlyEndDate",
      "complexMonthlyOccurrenceCount", "complexYearly", "complexYearlyEndDate",
      "complexYearlyOccurrenceCount",
    ]
  ),
  "RelativeDateTimeFormatter": GeneratedAPITypeContract(
    instanceProperties: ["locale"],
    instanceMethods: ["string", "useNamedDateTimeStyle", "useNumericDateTimeStyle"],
    asyncInstanceMethods: [],
    staticMethods: [],
    asyncStaticMethods: [],
    runtimeMembers: ["locale", "string", "useNamedDateTimeStyle", "useNumericDateTimeStyle"]
  ),
  "Reminder": GeneratedAPITypeContract(
    instanceProperties: [
      "calendar", "completionDate", "creationDate", "dueDate", "dueDateIncludesTime", "identifier",
      "isCompleted", "isOverdue", "notes", "priority", "title",
    ],
    instanceMethods: ["addRecurrenceRule", "remove", "removeAllRecurrenceRules", "save"],
    asyncInstanceMethods: [],
    staticMethods: [],
    asyncStaticMethods: [
      "all", "allCompleted", "allDueBetween", "allDueLastWeek", "allDueNextWeek", "allDueThisWeek",
      "allDueToday", "allDueTomorrow", "allDueYesterday", "allIncomplete", "completedBetween",
      "completedDueBetween", "completedDueLastWeek", "completedDueNextWeek", "completedDueThisWeek",
      "completedDueToday", "completedDueTomorrow", "completedDueYesterday", "completedLastWeek",
      "completedThisWeek", "completedToday", "incompleteDueBetween", "incompleteDueLastWeek",
      "incompleteDueNextWeek", "incompleteDueThisWeek", "incompleteDueToday",
      "incompleteDueTomorrow", "incompleteDueYesterday", "scheduled",
    ],
    runtimeMembers: [
      "identifier", "title", "notes", "isCompleted", "isOverdue", "priority", "dueDate",
      "dueDateIncludesTime", "completionDate", "creationDate", "calendar", "addRecurrenceRule",
      "removeAllRecurrenceRules", "save", "remove", "scheduled", "all", "allCompleted",
      "allIncomplete", "allDueToday", "completedDueToday", "incompleteDueToday", "allDueTomorrow",
      "completedDueTomorrow", "incompleteDueTomorrow", "allDueYesterday", "completedDueYesterday",
      "incompleteDueYesterday", "allDueThisWeek", "completedDueThisWeek", "incompleteDueThisWeek",
      "allDueNextWeek", "completedDueNextWeek", "incompleteDueNextWeek", "allDueLastWeek",
      "completedDueLastWeek", "incompleteDueLastWeek", "completedToday", "completedThisWeek",
      "completedLastWeek", "allDueBetween", "completedDueBetween", "incompleteDueBetween",
      "completedBetween",
    ]
  ),
  "Request": GeneratedAPITypeContract(
    instanceProperties: [
      "allowInsecureRequest", "body", "headers", "method", "onRedirect", "response",
      "timeoutInterval", "url",
    ],
    instanceMethods: [
      "addFileDataToMultipart", "addFileToMultipart", "addImageToMultipart",
      "addParameterToMultipart",
    ],
    asyncInstanceMethods: ["load", "loadImage", "loadJSON", "loadString"],
    staticMethods: [],
    asyncStaticMethods: [],
    runtimeMembers: [
      "url", "method", "headers", "body", "timeoutInterval", "onRedirect", "response",
      "allowInsecureRequest", "load", "loadString", "loadJSON", "loadImage",
      "addParameterToMultipart", "addFileDataToMultipart", "addFileToMultipart",
      "addImageToMultipart",
    ]
  ),
  "Safari": GeneratedAPITypeContract(
    instanceProperties: [],
    instanceMethods: [],
    asyncInstanceMethods: [],
    staticMethods: ["open"],
    asyncStaticMethods: ["openInApp"],
    runtimeMembers: ["openInApp", "open"]
  ),
  "Script": GeneratedAPITypeContract(
    instanceProperties: [],
    instanceMethods: [],
    asyncInstanceMethods: [],
    staticMethods: ["complete", "name", "setShortcutOutput", "setWidget"],
    asyncStaticMethods: [],
    runtimeMembers: ["name", "complete", "setShortcutOutput", "setWidget"]
  ),
  "SFSymbol": GeneratedAPITypeContract(
    instanceProperties: ["image"],
    instanceMethods: [
      "applyBlackWeight", "applyBoldWeight", "applyFont", "applyHeavyWeight", "applyLightWeight",
      "applyMediumWeight", "applyRegularWeight", "applySemiboldWeight", "applyThinWeight",
      "applyUltraLightWeight",
    ],
    asyncInstanceMethods: [],
    staticMethods: ["named"],
    asyncStaticMethods: [],
    runtimeMembers: [
      "image", "named", "applyFont", "applyUltraLightWeight", "applyThinWeight", "applyLightWeight",
      "applyRegularWeight", "applyMediumWeight", "applySemiboldWeight", "applyBoldWeight",
      "applyHeavyWeight", "applyBlackWeight",
    ]
  ),
  "ShareSheet": GeneratedAPITypeContract(
    instanceProperties: [],
    instanceMethods: [],
    asyncInstanceMethods: [],
    staticMethods: [],
    asyncStaticMethods: ["present"],
    runtimeMembers: ["present"]
  ),
  "Size": GeneratedAPITypeContract(
    instanceProperties: ["height", "width"],
    instanceMethods: [],
    asyncInstanceMethods: [],
    staticMethods: [],
    asyncStaticMethods: [],
    runtimeMembers: ["width", "height"]
  ),
  "Speech": GeneratedAPITypeContract(
    instanceProperties: [],
    instanceMethods: [],
    asyncInstanceMethods: [],
    staticMethods: ["speak"],
    asyncStaticMethods: [],
    runtimeMembers: ["speak"]
  ),
  "TextField": GeneratedAPITypeContract(
    instanceProperties: ["font", "isSecure", "placeholder", "text", "textColor"],
    instanceMethods: [
      "centerAlignText", "leftAlignText", "rightAlignText", "setDecimalPadKeyboard",
      "setDefaultKeyboard", "setEmailAddressKeyboard", "setNumberPadKeyboard",
      "setNumbersAndPunctuationKeyboard", "setPhonePadKeyboard", "setTwitterKeyboard",
      "setURLKeyboard", "setWebSearchKeyboard",
    ],
    asyncInstanceMethods: [],
    staticMethods: [],
    asyncStaticMethods: [],
    runtimeMembers: [
      "text", "placeholder", "isSecure", "textColor", "font", "setDefaultKeyboard",
      "setNumberPadKeyboard", "setDecimalPadKeyboard", "setNumbersAndPunctuationKeyboard",
      "setPhonePadKeyboard", "setWebSearchKeyboard", "setEmailAddressKeyboard", "setURLKeyboard",
      "setTwitterKeyboard", "leftAlignText", "centerAlignText", "rightAlignText",
    ]
  ),
  "Timer": GeneratedAPITypeContract(
    instanceProperties: ["repeats", "timeInterval"],
    instanceMethods: ["invalidate", "schedule"],
    asyncInstanceMethods: [],
    staticMethods: ["schedule"],
    asyncStaticMethods: [],
    runtimeMembers: ["timeInterval", "repeats", "schedule", "invalidate", "schedule"]
  ),
  "UITable": GeneratedAPITypeContract(
    instanceProperties: ["showSeparators"],
    instanceMethods: ["addRow", "reload", "removeAllRows", "removeRow"],
    asyncInstanceMethods: ["present"],
    staticMethods: [],
    asyncStaticMethods: [],
    runtimeMembers: ["showSeparators", "addRow", "removeRow", "removeAllRows", "reload", "present"]
  ),
  "UITableCell": GeneratedAPITypeContract(
    instanceProperties: [
      "dismissOnTap", "onTap", "subtitleColor", "subtitleFont", "titleColor", "titleFont",
      "widthWeight",
    ],
    instanceMethods: ["centerAligned", "leftAligned", "rightAligned"],
    asyncInstanceMethods: [],
    staticMethods: ["button", "image", "imageAtURL", "text"],
    asyncStaticMethods: [],
    runtimeMembers: [
      "widthWeight", "onTap", "dismissOnTap", "titleColor", "subtitleColor", "titleFont",
      "subtitleFont", "text", "image", "imageAtURL", "button", "leftAligned", "centerAligned",
      "rightAligned",
    ]
  ),
  "UITableRow": GeneratedAPITypeContract(
    instanceProperties: [
      "backgroundColor", "cellSpacing", "dismissOnSelect", "height", "isHeader", "onSelect",
    ],
    instanceMethods: ["addButton", "addCell", "addImage", "addImageAtURL", "addText"],
    asyncInstanceMethods: [],
    staticMethods: [],
    asyncStaticMethods: [],
    runtimeMembers: [
      "cellSpacing", "height", "isHeader", "dismissOnSelect", "onSelect", "backgroundColor",
      "addCell", "addText", "addImage", "addImageAtURL", "addButton",
    ]
  ),
  "URLScheme": GeneratedAPITypeContract(
    instanceProperties: [],
    instanceMethods: [],
    asyncInstanceMethods: [],
    staticMethods: [
      "allParameters", "forOpeningScript", "forOpeningScriptSettings", "forRunningScript",
      "parameter",
    ],
    asyncStaticMethods: [],
    runtimeMembers: [
      "allParameters", "parameter", "forOpeningScript", "forOpeningScriptSettings",
      "forRunningScript",
    ]
  ),
  "UUID": GeneratedAPITypeContract(
    instanceProperties: [],
    instanceMethods: [],
    asyncInstanceMethods: [],
    staticMethods: ["string"],
    asyncStaticMethods: [],
    runtimeMembers: ["string"]
  ),
  "WebView": GeneratedAPITypeContract(
    instanceProperties: ["shouldAllowRequest"],
    instanceMethods: [],
    asyncInstanceMethods: [
      "evaluateJavaScript", "getHTML", "loadFile", "loadHTML", "loadRequest", "loadURL", "present",
      "waitForLoad",
    ],
    staticMethods: [],
    asyncStaticMethods: ["loadFile", "loadHTML", "loadURL"],
    runtimeMembers: [
      "shouldAllowRequest", "loadHTML", "loadFile", "loadURL", "loadURL", "loadRequest", "loadHTML",
      "loadFile", "evaluateJavaScript", "getHTML", "present", "waitForLoad",
    ]
  ),
  "WidgetDate": GeneratedAPITypeContract(
    instanceProperties: [
      "date", "font", "lineLimit", "minimumScaleFactor", "shadowColor", "shadowOffset",
      "shadowRadius", "textColor", "textOpacity", "url",
    ],
    instanceMethods: [
      "applyDateStyle", "applyOffsetStyle", "applyRelativeStyle", "applyTimerStyle",
      "applyTimeStyle", "centerAlignText", "leftAlignText", "rightAlignText",
    ],
    asyncInstanceMethods: [],
    staticMethods: [],
    asyncStaticMethods: [],
    runtimeMembers: [
      "date", "textColor", "font", "textOpacity", "lineLimit", "minimumScaleFactor", "shadowColor",
      "shadowRadius", "shadowOffset", "url", "leftAlignText", "centerAlignText", "rightAlignText",
      "applyTimeStyle", "applyDateStyle", "applyRelativeStyle", "applyOffsetStyle",
      "applyTimerStyle",
    ]
  ),
  "WidgetImage": GeneratedAPITypeContract(
    instanceProperties: [
      "borderColor", "borderWidth", "containerRelativeShape", "cornerRadius", "image",
      "imageOpacity", "imageSize", "resizable", "tintColor", "url",
    ],
    instanceMethods: [
      "applyFillingContentMode", "applyFittingContentMode", "centerAlignImage", "leftAlignImage",
      "rightAlignImage",
    ],
    asyncInstanceMethods: [],
    staticMethods: [],
    asyncStaticMethods: [],
    runtimeMembers: [
      "image", "resizable", "imageSize", "imageOpacity", "cornerRadius", "borderWidth",
      "borderColor", "containerRelativeShape", "tintColor", "url", "leftAlignImage",
      "centerAlignImage", "rightAlignImage", "applyFittingContentMode", "applyFillingContentMode",
    ]
  ),
  "WidgetSpacer": GeneratedAPITypeContract(
    instanceProperties: ["length"],
    instanceMethods: [],
    asyncInstanceMethods: [],
    staticMethods: [],
    asyncStaticMethods: [],
    runtimeMembers: ["length"]
  ),
  "WidgetStack": GeneratedAPITypeContract(
    instanceProperties: [
      "backgroundColor", "backgroundGradient", "backgroundImage", "borderColor", "borderWidth",
      "cornerRadius", "size", "spacing", "url",
    ],
    instanceMethods: [
      "addDate", "addImage", "addSpacer", "addStack", "addText", "bottomAlignContent",
      "centerAlignContent", "layoutHorizontally", "layoutVertically", "setPadding",
      "topAlignContent", "useDefaultPadding",
    ],
    asyncInstanceMethods: [],
    staticMethods: [],
    asyncStaticMethods: [],
    runtimeMembers: [
      "backgroundColor", "backgroundImage", "backgroundGradient", "spacing", "size", "cornerRadius",
      "borderWidth", "borderColor", "url", "addText", "addDate", "addImage", "addSpacer",
      "addStack", "setPadding", "useDefaultPadding", "topAlignContent", "centerAlignContent",
      "bottomAlignContent", "layoutHorizontally", "layoutVertically",
    ]
  ),
  "WidgetText": GeneratedAPITypeContract(
    instanceProperties: [
      "font", "lineLimit", "minimumScaleFactor", "shadowColor", "shadowOffset", "shadowRadius",
      "text", "textColor", "textOpacity", "url",
    ],
    instanceMethods: ["centerAlignText", "leftAlignText", "rightAlignText"],
    asyncInstanceMethods: [],
    staticMethods: [],
    asyncStaticMethods: [],
    runtimeMembers: [
      "text", "textColor", "font", "textOpacity", "lineLimit", "minimumScaleFactor", "shadowColor",
      "shadowRadius", "shadowOffset", "url", "leftAlignText", "centerAlignText", "rightAlignText",
    ]
  ),
  "XMLParser": GeneratedAPITypeContract(
    instanceProperties: [
      "didEndDocument", "didEndElement", "didStartDocument", "didStartElement", "foundCharacters",
      "parseErrorOccurred", "string",
    ],
    instanceMethods: ["parse"],
    asyncInstanceMethods: [],
    staticMethods: [],
    asyncStaticMethods: [],
    runtimeMembers: [
      "didStartDocument", "didEndDocument", "didStartElement", "didEndElement", "foundCharacters",
      "parseErrorOccurred", "string", "parse",
    ]
  ),
]
